# Generated by Django 5.0.7 on 2024-08-05 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'позиция', 'verbose_name_plural': 'позиция'},
        ),
        migrations.AlterModelOptions(
            name='leadership',
            options={'verbose_name': 'Лидер', 'verbose_name_plural': 'Лидер'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='acceptance',
            field=models.CharField(max_length=100, verbose_name='день поступления'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='employ.department', verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='имя Фамилия'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='image',
            field=models.ImageField(default='default/o1.jpg', upload_to='leadership/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='published_date',
            field=models.DateField(auto_now_add=True, verbose_name='время'),
        ),
    ]
