# Generated by Django 5.0.7 on 2024-08-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionschool',
            name='published_date',
            field=models.DateField(auto_now_add=True, verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='positionschool',
            name='title',
            field=models.CharField(max_length=100, verbose_name='позиция'),
        ),
    ]
