# Generated by Django 5.0.7 on 2024-08-05 16:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_positionschool_published_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoschool',
            options={'verbose_name': 'школы', 'verbose_name_plural': 'школы'},
        ),
        migrations.AlterModelOptions(
            name='officeschool',
            options={'verbose_name': 'лидерство', 'verbose_name_plural': 'лидерство'},
        ),
        migrations.AlterModelOptions(
            name='positionschool',
            options={'verbose_name': 'позиции', 'verbose_name_plural': 'позиции'},
        ),
        migrations.RemoveField(
            model_name='officeschool',
            name='last',
        ),
        migrations.RemoveField(
            model_name='officeschool',
            name='name',
        ),
        migrations.AddField(
            model_name='officeschool',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='имя Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='officeschool',
            name='acceptance',
            field=models.CharField(max_length=100, verbose_name='день поступления'),
        ),
        migrations.AlterField(
            model_name='officeschool',
            name='image',
            field=models.ImageField(default='default/o1.jpg', upload_to='offis/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='officeschool',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='officeschool',
            name='positiono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.positionschool', verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='officeschool',
            name='published_date',
            field=models.DateField(auto_now_add=True, verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='officeschool',
            name='wschool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.infoschool', verbose_name='школы'),
        ),
    ]
