# Generated by Django 5.0.7 on 2024-08-04 09:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
                ('name', models.CharField(max_length=255)),
                ('leader', models.CharField(max_length=255)),
                ('days', models.CharField(max_length=255)),
                ('meeting_time', models.CharField(max_length=255)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.infoschool')),
            ],
        ),
    ]
