# Generated by Django 5.0.7 on 2024-08-02 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('leader', models.CharField(max_length=255)),
                ('days', models.CharField(max_length=255)),
                ('meeting_time', models.CharField(max_length=255)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.infoschool')),
            ],
        ),
    ]
