# Generated by Django 5.0.7 on 2024-08-05 12:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_students'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'урок', 'verbose_name_plural': 'урок'},
        ),
        migrations.AlterField(
            model_name='club',
            name='days',
            field=models.CharField(max_length=255, verbose_name='день'),
        ),
        migrations.AlterField(
            model_name='club',
            name='leader',
            field=models.CharField(max_length=255, verbose_name='учитель'),
        ),
        migrations.AlterField(
            model_name='club',
            name='meeting_time',
            field=models.CharField(max_length=255, verbose_name='час'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=255, verbose_name='урок'),
        ),
        migrations.AlterField(
            model_name='club',
            name='students',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='студенты'),
        ),
        migrations.AlterField(
            model_name='club',
            name='wschool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.infoschool', verbose_name='школа'),
        ),
    ]
