# Generated by Django 5.0.7 on 2024-08-05 15:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slevel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infolevel',
            options={'verbose_name': 'организация', 'verbose_name_plural': 'организация'},
        ),
        migrations.AlterModelOptions(
            name='officelevel',
            options={'verbose_name': 'лидерство', 'verbose_name_plural': 'лидерство'},
        ),
        migrations.AlterModelOptions(
            name='positionlevel',
            options={'verbose_name': 'позиции', 'verbose_name_plural': 'позиции'},
        ),
        migrations.RemoveField(
            model_name='officelevel',
            name='last',
        ),
        migrations.RemoveField(
            model_name='officelevel',
            name='name',
        ),
        migrations.AddField(
            model_name='officelevel',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='имя Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infolevel',
            name='number_ch',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='количество студентов'),
        ),
        migrations.AlterField(
            model_name='infolevel',
            name='number_ep',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='количество учителей'),
        ),
        migrations.AlterField(
            model_name='infolevel',
            name='published_date',
            field=models.DateField(auto_now_add=True, verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='infolevel',
            name='title',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Номер школы'),
        ),
        migrations.AlterField(
            model_name='infolevel',
            name='titletext',
            field=models.CharField(max_length=200, verbose_name='Название школы'),
        ),
        migrations.AlterField(
            model_name='officelevel',
            name='acceptance',
            field=models.CharField(max_length=100, verbose_name='день поступления'),
        ),
        migrations.AlterField(
            model_name='officelevel',
            name='image',
            field=models.ImageField(upload_to='offis/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='officelevel',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='officelevel',
            name='positiono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slevel.positionlevel', verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='officelevel',
            name='published_date',
            field=models.DateField(auto_now_add=True, verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='officelevel',
            name='wslevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slevel.infolevel', verbose_name='Д.О.У'),
        ),
        migrations.AlterField(
            model_name='positionlevel',
            name='published_date',
            field=models.DateField(auto_now_add=True, verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='positionlevel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='позиция'),
        ),
    ]
