# Generated by Django 5.0.7 on 2024-08-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='statestic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schools', models.CharField(max_length=200)),
                ('techers', models.CharField(max_length=200)),
                ('student', models.CharField(max_length=200)),
                ('educati', models.CharField(max_length=200)),
                ('techedu', models.CharField(max_length=200)),
                ('chiledu', models.CharField(max_length=200)),
            ],
        ),
    ]
