# Generated by Django 5.0.7 on 2024-08-05 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statestic',
            options={'verbose_name': 'статистика', 'verbose_name_plural': 'статистика'},
        ),
        migrations.AlterField(
            model_name='statestic',
            name='chiledu',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='ученик Д.О.У'),
        ),
        migrations.AlterField(
            model_name='statestic',
            name='educati',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='Д.О.У'),
        ),
        migrations.AlterField(
            model_name='statestic',
            name='schools',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='школа'),
        ),
        migrations.AlterField(
            model_name='statestic',
            name='student',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='ученик'),
        ),
        migrations.AlterField(
            model_name='statestic',
            name='techedu',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='учитель Д.О.У'),
        ),
        migrations.AlterField(
            model_name='statestic',
            name='techers',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='учитель'),
        ),
    ]
