# Generated by Django 5.0.7 on 2024-08-05 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statest', '0002_alter_statestic_options_alter_statestic_chiledu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statestic',
            name='chiledu',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='ученик Д.О.У'),
        ),
        migrations.AlterField(
            model_name='statestic',
            name='educati',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='Д.О.У'),
        ),
        migrations.AlterField(
            model_name='statestic',
            name='schools',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='школа'),
        ),
        migrations.AlterField(
            model_name='statestic',
            name='student',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='ученик'),
        ),
        migrations.AlterField(
            model_name='statestic',
            name='techedu',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='учитель Д.О.У'),
        ),
        migrations.AlterField(
            model_name='statestic',
            name='techers',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='учитель'),
        ),
    ]
