# Generated by Django 5.0.7 on 2024-08-05 12:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'список', 'verbose_name_plural': 'список'},
        ),
        migrations.AlterModelOptions(
            name='wclases',
            options={'verbose_name': 'класс', 'verbose_name_plural': 'класс'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(help_text='PDF или Word', upload_to='lesson/', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published_date',
            field=models.DateField(auto_now_add=True, verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='wclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.wclases', verbose_name='класс'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='wschool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.infoschool', verbose_name='школа'),
        ),
        migrations.AlterField(
            model_name='wclases',
            name='published_date',
            field=models.DateField(auto_now_add=True, verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='wclases',
            name='title',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='класс'),
        ),
    ]
